-- v0.2 curated expansion. Idempotent upsert only; does not rewrite analytics tables.
insert into public.dumpster_atlas_resources
(id,name,category,tags,address,city,latitude,longitude,description,access_note,source_url,verified_at,active)
values
('zanker-mpf','Zanker Material Processing Facility','recycling',array['recycling','construction','yard-waste','wood','concrete'],'675 Los Esteros Rd, San Jose, CA 95134','San Jose',37.43199,-121.95364,'Public construction, demolition, wood, concrete and yard-material processing facility listed in CalRecycle SWIS.','Industrial public facility with scale lanes. Confirm current accepted materials, fees, and hours before travel. A pin is not permission to enter restricted work areas.','https://www2.calrecycle.ca.gov/SolidWaste/Site/Summary/3386','2026-09-16',true),
('second-harvest-cypress','Second Harvest of Silicon Valley — Cypress Center','food',array['food','food-assistance','donations','produce'],'4001 N First St, San Jose, CA 95134','San Jose',37.41278,-121.95194,'Second Harvest produce/distribution facility published on the organization''s contact page.','This is an operations and donation address. Use Second Harvest''s current food-finder for recipient services before travel.','https://www.shfb.org/about-us/contact-us/','2026-09-16',true),
('sacred-heart-cs','Sacred Heart Community Services','food',array['food','clothing','community','assistance'],'1381 S 1st St, San Jose, CA 95110','San Jose',37.3149,-121.8716,'Long-running San Jose community organization offering food, clothing and related neighbor services.','Public nonprofit campus. Program hours and eligibility change; confirm on the organization''s site before travel.','https://sacredheartcs.org/contact/','2026-09-16',true),
('marthas-kitchen','Martha''s Kitchen','food',array['food','meals','community'],'311 Willow St, San Jose, CA 95110','San Jose',37.3382,-121.8963,'San Jose meal program and community kitchen listed as a public food resource.','Public meal/donation site. Confirm current meal times and donation rules before travel.','https://www.marthas-kitchen.org/','2026-09-16',true),
('loaves-fishes-sj','Loaves & Fishes Family Kitchen','food',array['food','meals','community'],'1501 Berger Dr, San Jose, CA 95112','San Jose',37.3645,-121.8904,'Family kitchen serving prepared meals in San Jose.','Public meal program. Confirm current serving hours and locations on the organization''s site.','https://www.loavesfishes.org/contact/','2026-09-16',true),
('cityteam-sj','CityTeam San Jose','food',array['food','shelter','community','assistance'],'1297 N 13th St, San Jose, CA 95112','San Jose',37.3618,-121.8919,'CityTeam San Jose campus for meals and related community services.','Public nonprofit campus. Services and intake rules change; confirm on CityTeam''s site before travel.','https://cityteam.org/san-jose/','2026-09-16',true),
('goodwill-sv-sj','Goodwill of Silicon Valley — San Jose Store','reuse',array['reuse','clothing','furniture','donations'],'1080 N 7th St, San Jose, CA 95112','San Jose',37.3614,-121.8996,'Goodwill retail and donation location for reusable clothing and household goods.','Public thrift/donation store. Confirm donation acceptance and hours before dropping large items.','https://goodwillsv.org/donate/','2026-09-16',true),
('salvation-army-sj','The Salvation Army San Jose','reuse',array['reuse','clothing','food','community'],'702 W Taylor St, San Jose, CA 95126','San Jose',37.3406,-121.9128,'Salvation Army San Jose location for donations and community programs.','Public nonprofit campus. Confirm current donation and program hours before travel.','https://sanjose.salvationarmy.org/','2026-09-16',true),
('hhw-san-jose','Santa Clara County Household Hazardous Waste — San Jose','recycling',array['hhw','paint','batteries','electronics','recycling'],'1608 Las Plumas Ave, San Jose, CA 95133','San Jose',37.3595,-121.8681,'County household hazardous waste drop-off program for residents.','Appointment or program rules often apply. Bring ID if required. Confirm accepted items on the county HHW page before travel.','https://hhw.org/','2026-09-16',true),
('sj-esd','City of San Jose Environmental Services','recycling',array['recycling','city-services','garbage','recycle-plus'],'200 E Santa Clara St, San Jose, CA 95113','San Jose',37.3382,-121.8863,'City environmental-services office and official source for Recycle Plus rules and facility referrals.','This is a city office, not a dumpster. Use it for official program rules and current drop-off referrals.','https://www.sanjoseca.gov/your-government/departments-offices/environmental-services','2026-09-16',true),
('smart-station','SMaRT Station','recycling',array['recycling','sunnyvale','mountain-view','palo-alto'],'301 Carl Rd, Sunnyvale, CA 94089','Sunnyvale',37.4163,-122.0157,'Sunnyvale Materials Recovery and Transfer Station serving Sunnyvale, Mountain View and Palo Alto.','Public transfer/recycling facility. Confirm resident eligibility, fees, and accepted materials before travel.','https://www.sunnyvale.ca.gov/our-city/departments/public-works/garbage-recycling','2026-09-16',true),
('west-valley-cs','West Valley Community Services','food',array['food','assistance','cupertino','community'],'10104 Vista Dr, Cupertino, CA 95014','Cupertino',37.3229,-122.0382,'West Valley Community Services food and neighbor-support programs.','Public nonprofit. Confirm current pantry hours and eligibility before travel.','https://www.wvcommunityservices.org/','2026-09-16',true),
('sunnyvale-cs','Sunnyvale Community Services','food',array['food','assistance','sunnyvale','community'],'725 Kifer Rd, Sunnyvale, CA 94086','Sunnyvale',37.3734,-122.0123,'Sunnyvale Community Services food and emergency-assistance programs.','Public nonprofit. Confirm current pantry and assistance hours before travel.','https://svcommunityservices.org/','2026-09-16',true),
('homefirst-boccardo','HomeFirst Boccardo Welcome Center','food',array['shelter','community','assistance','food'],'2011 Little Orchard St, San Jose, CA 95125','San Jose',37.3048,-121.8715,'HomeFirst welcome center for shelter and related neighbor services.','Public nonprofit campus. Intake rules change; confirm current services on HomeFirst''s site before travel.','https://www.homefirstscc.org/','2026-09-16',true),
('bill-wilson-center','Bill Wilson Center','food',array['youth','community','assistance'],'3490 The Alameda, Santa Clara, CA 95050','Santa Clara',37.3526,-121.9378,'Bill Wilson Center youth and family services campus in Santa Clara.','Public nonprofit campus. Confirm current program hours and who the site serves before travel.','https://www.billwilsoncenter.org/','2026-09-16',true),
('our-city-forest','Our City Forest','reuse',array['trees','yard-waste','community','reuse'],'345 S 11th St, San Jose, CA 95112','San Jose',37.3316,-121.8754,'San Jose urban-forestry nonprofit and community tree resource.','Public nonprofit yard/office. Confirm volunteer, giveaway, or drop-off events on the organization''s site.','https://www.ourcityforest.org/','2026-09-16',true),
('dst-sj','Downtown Streets Team — San Jose','community',array['community','assistance','reuse'],'1671 S 7th St, San Jose, CA 95112','San Jose',37.3142,-121.8668,'Downtown Streets Team San Jose site connecting neighbors to work and support.','Public nonprofit site. Confirm current program hours before travel.','https://streetsteam.org/','2026-09-16',true),
('healthtrust','The Health Trust','food',array['food','health','community'],'3180 Newberry Dr, San Jose, CA 95118','San Jose',37.2589,-121.8806,'The Health Trust offices and community-health programs, including food-access work.','This is an organization office plus program hub. Confirm which services happen on-site before travel.','https://healthtrust.org/','2026-09-16',true),
('catholic-charities-scc','Catholic Charities of Santa Clara County','food',array['food','assistance','community'],'2625 Zanker Rd, San Jose, CA 95134','San Jose',37.3947,-121.9285,'Countywide Catholic Charities campus for food and family-support programs.','Public nonprofit campus. Confirm current program hours and eligibility before travel.','https://www.catholiccharitiesscc.org/','2026-09-16',true),
('south-valley-fish','South Valley FISH','food',array['food','assistance','south-county'],'5100 Camden Ave, San Jose, CA 95124','San Jose',37.2396,-121.8968,'South Valley FISH food-assistance program listed as a public pantry resource.','Public pantry program. Confirm current distribution hours and any donation limits before travel.','https://www.southvalleyfish.org/','2026-09-16',true)
on conflict (id) do update set
  name=excluded.name,
  category=excluded.category,
  tags=excluded.tags,
  address=excluded.address,
  city=excluded.city,
  latitude=excluded.latitude,
  longitude=excluded.longitude,
  description=excluded.description,
  access_note=excluded.access_note,
  source_url=excluded.source_url,
  verified_at=excluded.verified_at,
  active=excluded.active,
  updated_at=now();
